name: Brendan Scarano
description: Brendan Scarano Site

url: "http://localhost:4000"

paginate: 10

# markdown: rdiscount
markdown: redcarpet
permalink: pretty
highlighter: pygments

sass:
  sass_dir: _sass
  style: compressed