name: Brendan Scarano
description: Brendan Scarano Site

url: "http://localhost:4000"

# paginate: 10

# markdown: rdiscount
markdown: kramdown
permalink: pretty
highlighter: pygments

twitter_username:     b_joe_s
github_username:      brendanscarano
linkedin_username:    brendanscarano

sass:
  sass_dir: _sass
  style: compressed
